LIBRARY_TYPE_IMAGE = 'image'
LIBRARY_TYPE_AUDIO = 'audio'
LIBRARY_TYPE_VIDEO = 'video'

FILE_TYPE_IMAGE = 'image'
FILE_TYPE_AUDIO = 'audio'
FILE_TYPE_VIDEO = 'video'

LIBRARY_IMAGE_RESIZE_TASK = 'LIBRARY_IMAGE_RESIZE'

