PKSPB_DUSER = '2ZbOCCr9SZjfoDxKq19AilGNPJuCE'
PKSPB_DPASS = 'xXgUw16hSjrbghoBE5zNYUmxKrOHO'
PKSPB_ID = '291'

ROBOKASSA_LOGIN = 'ModnoeMesto'
ROBOKASSA_PASSWORD1 = 'G$5g7klop-gret67'
ROBOKASSA_PASSWORD2 = 'G$5g7klop-gret67'
ROBOKASSA_TEST_MODE = True
ROBOKASSA_USE_POST = False
ROBOKASSA_EXTRA_PARAMS = ['user_id', ]

TIME_INTERVAL_NOTIFY = 60

import sys
if 'test' in sys.argv:
    TIME_INTERVAL_NOTIFY = 1