PKSPB_DUSER = '2ZbOCCr9SZjfoDxKq19AilGNPJuCE'
PKSPB_DPASS = 'xXgUw16hSjrbghoBE5zNYUmxKrOHO'
PKSPB_ID = '291'

ROBOKASSA_LOGIN = 'EliasTest'
ROBOKASSA_PASSWORD1 = 'zhrbqltym0'
ROBOKASSA_PASSWORD2 = 'zhrbqltym0'
ROBOKASSA_TEST_MODE = True
ROBOKASSA_USE_POST = False
TIME_INTERVAL_NOTIFY = 60