# -*- coding: utf-8 -*-
CAPTCHA_BACKGROUND_COLOR = (156, 226, 240)
CAPTCHA_FOREGROUND_COLORS = ((104, 103, 103),)
CAPTCHA_SIZE = (150, 100)
CAPTCHA_ALT = 'no robots here'
CAPTCHA_DEFAULT_ERROR_MESSAGE = u'Код неверный, попробуйте ещё раз.'
CAPTCHA_LENGTH = 4
CAPTCHA_COLORIZE_SYMBOLS = False