#! /bin/sh

### BEGIN INIT INFO
# Provides:          node
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO

set -e

kill_if_exist () {
	for PID in `ps ax | grep  "$1" | grep -v grep | cut -c-6`
	do
		kill -9 $PID
	done
}

case "$1" in
  start|restart)
	kill_if_exist "node server-io.js"
	cd /var/socnet/appserver/app/chat
	node server-io.js > /dev/null 2>/var/log/chat.log &
	;;
  stop)
	kill_if_exist "node server-io.js"
	;;
  *)
	echo "Usage: /etc/init.d/node {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0