#! /bin/sh

### BEGIN INIT INFO
# Provides:          socnet
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO

set -e

kill_if_exist () {
	for PID in `ps ax | grep  "$1" | grep -v grep | cut -c-6`
	do
		kill -9 $PID
	done
}

case "$1" in
  start|restart)
	kill_if_exist "node server-io.js"
	cd /var/socnet/appserver/app/chat
	node server-io.js > /dev/null 2>&1 &
	cd /var/socnet/appserver/app
	. venv/bin/activate
	kill_if_exist "manage.py celeryd"
	python manage.py celeryd > /dev/null 2>&1 &
	kill_if_exist "uwsgi"
	uwsgi -s /tmp/socnet-uwsgi.sock -C -H venv -x django.xml -M -p 16 -l 16384 > /dev/null 2>/tmp/socnet-uwsgi.log &
	;;
  stop)
	kill_if_exist "uwsgi"
	kill_if_exist "manage.py celeryd"
	kill_if_exist "node server-io.js"
	;;
  *)
	echo "Usage: /etc/init.d/socnet {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
